using Prolly.Patterns;
using Prolly.Patterns.CircuitBreaker;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Prolly.Commands
{
    /// <summary>
    /// A group to which a ProllyCommand belongs. All Commands in a certain group share the same CircuitBreaker.
    /// CommandGroup's are generated by the CommandGroupFactory
    /// </summary>
    public class CommandGroup
    {
        public string Name { get; private set; }

        public ICircuitBreaker CircuitBreaker { get; private set; }

        public CommandGroup(string name, ICircuitBreaker circuitBreaker)
        {
            Name = name;
            CircuitBreaker = circuitBreaker;
        }
    }
}
